### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by EasonC13** [iotaledger/chronicle.rs#76]
## Bug description

Walking through [Tutorial](https://docs.iota.org/docs/chronicle/1.1/tutorials/run-a-permanode) and met the problem shown below when I running 

`RUST_BACKTRACE=1 cargo run --release --features "mainnet" --example permanode ./permanode/config.toml`

## Version

e0013f6

- Version:

rustc 1.50.0 (cb75ad5db 2021-02-10)
cargo 1.50.0 (f04e7fab7 2021-02-04)

What hardware are you using?

- OS and version: Ubuntu 18.04
- RAM: 32GB
- Number of cores: 8

## Node Settings (delete if not relevant)

I change the Scylla cluster's addresses.

`
[scylla_cluster]
addresses = ["127.0.0.1:9042"] # scylla docker instance
`

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. install chronicle.rs at Ubuntu by following [Tutorial](https://docs.iota.org/docs/chronicle/1.1/tutorials/run-a-permanode)

## Expected behaviour

It should run well without ERROR.

## Actual behaviour

It show error.

## Errors

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', MY_PATH/chronicle.rs/chronicle-storage/src/ring/mod.rs:250:14

stack backtrace:
[2021-02-24][08:42:26][chronicle_storage::stage::reporter][INFO] address: 127.0.0.1:9042, shard_id: 0, reporter_id: 0, received session: 1
[2021-02-24][08:42:26][chronicle_storage::stage::reporter][INFO] address: 127.0.0.1:9042, shard_id: 0, reporter_id: 1, received session: 1
[2021-02-24][08:42:26][chronicle_storage::stage::reporter][INFO] address: 127.0.0.1:9042, shard_id: 1, reporter_id: 1, received session: 1
[2021-02-24][08:42:26][chronicle_storage::stage::reporter][INFO] address: 127.0.0.1:9042, shard_id: 1, reporter_id: 0, received session: 1
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: <([u8; 5],u8,u8) as chronicle_storage::ring::SmartId>::send_reporter
   4: <std::collections::hash::map::HashMap<alloc::string::String,alloc::vec::Vec<([u8; 5],u8,u8)>> as chronicle_storage::ring::Endpoints>::send
   5: chronicle_storage::ring::Ring::local_random_replica
   6: std::thread::local::LocalKey<T>::with
   7: chronicle_storage::ring::Ring::send_local_random_replica
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: permanode::main::{{closure}}
  10: tokio::runtime::enter::Enter::block_on
  11: tokio::runtime::thread_pool::ThreadPool::block_on
  12: tokio::runtime::context::enter
  13: permanode::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Debug

In order to Debug, I add the following codes to line 246-247 at chronicle.rs/chronicle-storage/src/ring/mod.rs

```
        println!("{:?}", &registry);
        println!("{:?}", (&self.0, &registry.get_mut(&self.0)));
```

the output is shown below:

```
{[127, 0, 0, 1, 1]: {1: UnboundedSender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x7f0d8800e0e0, tail_position: 1 }, semaphore: 0, rx_waker: AtomicWaker, tx_count: 7, rx_fields: "..." }, permit: () } }, 0: UnboundedSender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x7f0d8800d890, tail_position: 1 }, semaphore: 0, rx_waker: AtomicWaker, tx_count: 7, rx_fields: "..." }, permit: () } }}, [127, 0, 0, 1, 0]: {1: UnboundedSender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x7f0d9000a6e0, tail_position: 1 }, semaphore: 0, rx_waker: AtomicWaker, tx_count: 7, rx_fields: "..." }, permit: () } }, 0: UnboundedSender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x7f0d90001e80, tail_position: 1 }, semaphore: 0, rx_waker: AtomicWaker, tx_count: 7, rx_fields: "..." }, permit: () } }}}
([172, 17, 0, 4, 0], None)
```

The problem is that it returns None after `registry.get_mut(&self.0)`

**Comment by LouayKamel** [comment]
@EasonC13 Please make sure to use the next-0.1 branch and also use the broadcast_address of your Scylla node.

**Comment by LouayKamel** [comment]
I suppose if your scylla node is a docker instance, then use your docker instance address (172.x.x.x).

**Comment by EasonC13** [comment]
Thanks @LouayKamel .

The program run well after I change the Scylla cluster's addresses at examples/permanode/config.toml to:

```
[scylla_cluster]
addresses = ["172.17.0.4:9042"] # scylla docker instance
```

And now I finish the tutorial.
Thanks a lot!
